### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#102]
@halfempty 
I've dropped a vimeo link into the site, but it doesn't appear to be clicking to it. Anything I'm doing wrong?

**Comment by gehalber** [comment]
@halfempty 
Also, is the image in wp going to act as the play button cover for the video?

**Comment by halfempty** [comment]
@gehalber Couple things going on with the video...

1. The video share settings on the Vimeo side appear to be locked-down. It needs to be opened up for sharing, and then we need to grab the share URL (which is possibly different than the one we've got)

1b. Ideally, the video would be hosted on an official-looking Heckscher account, rather than the director's own account. (This isn't 100% my business tho, so maybe they have a reason for doing it this way.) But it does need a better title than "Heckscher_CUT_FINAL"

2. The template isn't programmed to have the image be a cover for the video. But we've done that in the past, so it is possible to do-- I can try to re-use some of our old code. Sounds like you'd like me to enable that?

**Comment by gehalber** [comment]
@halfempty 
Thanks! 
I'll setup a vimeo account this morning. You raise a good point that people will see this offsite. 

Re: 2
Yes, ideally we'd have the image be the cover so its nice a clean.

**Comment by halfempty** [comment]
@gehalber Update on this one-- Vimeo has changed their stuff, so the command to start the video playing is broken and I need to research / re-write it. 

The rest of it (having a cover image, play button, etc) is no problem.

Do you have a design for the play button that you'd like to use here? That will work overtop the graphic treatment?

**Comment by halfempty** [comment]
@gehalber Programming on the video wrapper is done.

https://www.heckscherfoundation.org/scholars/

**Comment by gehalber** [comment]
@halfempty
Here is the video graphic. It's an svg, but let me know if you need
something else.
https://www.dropbox.com/s/6ts9w3dan369npb/HF%20HF%20Scholars%20Site%20Play%20Button%2020171030%20HM-13.svg?dl=0

>
>

**Comment by halfempty** [comment]
@gehalber Okay, button is in! (I set it to highlight to yellow)
