### ISSUE TITLE
Our Approach Navigation

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#136]
This section should house:
Our Approach
Year in Review
Strategic Philanthropy Series

**Comment by halfempty** [comment]
@gehalber In the mockup it sort-of looks like the top navigation at the top of this section / page would include in-page anchor links to Venture Philanthropy, Proven Models and Quality of Life. Those are somewhat more difficult to achieve than our normal page links.

But I think what you're saying here negates that, so I'm going to go with what you're saying here, unless you say otherwise!

**Comment by halfempty** [comment]
Done
