### ISSUE TITLE
Logic of Highlighted Projects in Footer

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#79]
@gehalber Throughout the site we have a footer that highlights two random projects. Examining the logic, it looks like these are drawn from the pages which are 2 levels down from Projects itself.  For instance, given...

`Highlighed Projects -> Charter Schools -> Hebrew Charter School Center`

... it would be Charter Schools which has a chance to appear. Traditionally, that's made sense because Hebrew Charter School Center did not appear on its own page, but as an accordion on Charter Schools. But under the new design, those two pages can be viewed separately.

So, question: Should we keep this logic as it is? Or should pages at the 3rd level down also have a chance to appear?

**Comment by gehalber** [comment]
Good question. Projects at the third level down, like Hebrew Charter School Center, don't have their own images at the moment—though I think Heckscher is trying to change that in their administrative procedures. Since those highlighted projects footers require an image, let's only include projects at the second level for now. Thanks!

**Comment by gehalber** [comment]
@halfempty is this closable?
